"""add invoice number to sales

Revision ID: f94a120e36f2
Revises: db7405f5ebab
Create Date: 2026-03-09 10:17:01.608724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f94a120e36f2'
down_revision: Union[str, Sequence[str], None] = 'db7405f5ebab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('invoice_number', sa.String(), nullable=True))
    op.add_column('sales', sa.Column('invoice_date', sa.DateTime(), nullable=True))
    op.add_column('sales', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_invoice_number'), 'sales', ['invoice_number'], unique=True)
    op.create_foreign_key(None, 'sales', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_invoice_number'), table_name='sales')
    op.drop_column('sales', 'customer_id')
    op.drop_column('sales', 'invoice_date')
    op.drop_column('sales', 'invoice_number')
    # ### end Alembic commands ###
